// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smmlpmcdigtuudcsfsqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtbWxwbWNkaWd0dXVkY3Nmc3FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTg0NTQsImV4cCI6MjA1NjE3NDQ1NH0.NkCUngh74qjl00rWivp4y5VxasuCnGODWZKBcw3J3fo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);